Link to bibliography from citations in subfolders
francisco-perez-sorrosal/mdbook-bib pull request #34
Opened 2021-08-17 22:09 UTC by tchernobog

Citations in files lower than the book source root were producing an incorrect link because they weren't considering the relative path to the root.

This commits fixes it.

2021-08-17 22:36 UTC, francisco-perez-sorrosal commented
Hey @tchernobog thanks for this! By addressing this you are referring to the bug in #24 described by @mlange-42? If that's correct, I solved this too in #30 :-(

2021-08-17 22:42 UTC, tchernobog commented
Ach, it seems indeed the same issue. I must have overlooked it; I didn't know using an absolute path would be picked up from mdBook to convert it to the proper relative URL. That solution seems therefore simpler (I still haven't tried it though).

Feel free to close this then.

2021-08-17 22:48 UTC, francisco-perez-sorrosal commented
I'm sorry :-( But maybe we can reuse some of your tests in any case as you have some more scenarios with more nesting. If you want, I can commit #30 and you can rebase your changes and add your test additional test scenarios. In #30 I also created a test book that you can use for that too.

2021-08-18 00:08 UTC, francisco-perez-sorrosal commented
@tchernobog I've put all my PRs in master. You can check if my solution covers your cases and update this PR in case there's something wrong by rebasing on the current master branch. If you can confirm also that your books are working ok with these changes, maybe I can the release v0.0.4 on Sunday.

2021-08-18 07:01 UTC, tchernobog commented
@francisco-perez-sorrosal unfortunately the merged solution produces absolute paths (see screenshot).

![image](https://user-images.githubusercontent.com/18379816/129852701-12d89055-3e4f-4c8c-a2ae-43dc467f928f.png)

Obviously this doesn't work when you want to publish online the compiled book, or move it to a separate folder.
I kindly need to ask you to reconsider my patch for merging, after reverting yours.

2021-08-19 09:05 UTC, tchernobog commented
@francisco-perez-sorrosal I rebased my changes on top of yours.

2021-08-19 18:05 UTC, francisco-perez-sorrosal commented
@tchernobog Thanks Matteo! I was gonna tell you that! I'll test it as soon as I can and I'll merge ASAP

2021-08-20 06:47 UTC, francisco-perez-sorrosal commented on src/lib.rs
> +fn url_to_root(source_file: &std::path::Path) -> String {
Maybe `get_breadcrumbs_to_root` or simply `get_dotted_path_to_root` are better names for this function

2021-08-20 06:48 UTC, francisco-perez-sorrosal commented on src/lib.rs
> +    let s = &chapter.content;
Can you get rid of `s` and substitute it for `&chapter.content` below?

2021-08-20 06:48 UTC, francisco-perez-sorrosal commented on src/lib.rs
> +    for placeholder in find_placeholders(&s) {
^ here

2021-08-20 06:53 UTC, francisco-perez-sorrosal requested changes
Looks good to me. Minor changes below. Also after addressing the changes suggested, could you please execute `cargo fmt --` to format properly the changes?

Thanks!

2021-08-20 07:47 UTC, tchernobog commented
Done. I also added rusty-hook integration to enforce a formatting check on commit, and running tests on push.

2021-08-21 17:24 UTC, francisco-perez-sorrosal commented
There are minor `clippy` errors in the test.

2021-08-21 19:54 UTC, tchernobog commented
Thanks, clippy was missing the `--all-targets` flag.

2021-08-22 01:00 UTC, francisco-perez-sorrosal commented
Yeah in my laptop was even showing different issues

2021-08-22 01:01 UTC, francisco-perez-sorrosal approved these changes

2021-08-22 01:13 UTC, merged